/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stern;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author calin
 */
public class History extends javax.swing.JFrame {

    /**
     * Creates new form History
     */
    Connection con;
    public History() {
        initComponents();
        this.setLocationRelativeTo(null);
        createConnection();
        settable();
    }
    void createConnection(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //connect the database
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ptcdb", "root", "Calingasanjohnerick01");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void settable(){
        JTableHeader Theader = jTable1.getTableHeader();
        Theader.setBackground(new Color(69,69,69));
        Theader.setForeground(new Color(237,237,237));
       

        try {
            // para maka create ng statement object tapos yun maexecute yung sql querries
            Statement stmt = con.createStatement();
            
            //para ma execute ang selec query or para maretrieve yung mga data sa table sa sql 
            ResultSet rs = stmt.executeQuery("SELECT * FROM USERS");
            
            // para maloop yung mga result row by row
            while(rs.next()){
                //retrieve yung mga row sa result
                String date = rs.getString("Date");
                String time = rs.getString("Time");
                String From = rs.getString("From timezone");
                String To = rs.getString("To timezone");
                String datec = rs.getString("Date converted");
                String timec = rs.getString("Time converted");
                
                System.out.println("Date: " +date + " time: " + time + " From: " + From + " To: " + To + " Date converted: " + datec + " Time converted: " + timec);   
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                
                //add ng mga row sa table na yung lalabas ay yung nag retrieved na data galing sa sql
                model.addRow(new Object[]{date, time, From, To, datec, timec});

            }            
            stmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgtab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tabFeatures = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tabGlobalTimeConverter = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabPersonalizedTimeConverter = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tabTimeMasterSchedule = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tabHistory = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tabSettings = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel100 = new javax.swing.JPanel();
        timemasterscheduler = new javax.swing.JLabel();
        bgtimemasterscheduler = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1014, 635));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(null);

        bgtab.setBackground(new java.awt.Color(39, 39, 39));
        bgtab.setPreferredSize(new java.awt.Dimension(350, 600));
        bgtab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\calin\\OneDrive\\Documents\\NetBeansProjects\\STERN\\src\\Icon\\logo(welcome).png")); // NOI18N
        bgtab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        tabHome.setBackground(new java.awt.Color(39, 39, 39));
        tabHome.setPreferredSize(new java.awt.Dimension(200, 35));

        jLabel2.setBackground(new java.awt.Color(237, 237, 237));
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(237, 237, 237));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        jLabel2.setText("HOME");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout tabHomeLayout = new javax.swing.GroupLayout(tabHome);
        tabHome.setLayout(tabHomeLayout);
        tabHomeLayout.setHorizontalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tabHomeLayout.setVerticalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgtab.add(tabHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 350, 60));

        tabFeatures.setBackground(new java.awt.Color(39, 39, 39));
        tabFeatures.setPreferredSize(new java.awt.Dimension(200, 35));
        tabFeatures.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(237, 237, 237));
        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 237, 237));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("FEATURES");
        tabFeatures.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 350, 60));

        tabGlobalTimeConverter.setBackground(new java.awt.Color(39, 39, 39));
        tabGlobalTimeConverter.setPreferredSize(new java.awt.Dimension(200, 35));
        tabGlobalTimeConverter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(237, 237, 237));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 237, 237));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/global_time_converter.png"))); // NOI18N
        jLabel5.setText("GLOBAL TIME CONVERTER");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        tabGlobalTimeConverter.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabGlobalTimeConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 350, 60));

        tabPersonalizedTimeConverter.setBackground(new java.awt.Color(39, 39, 39));
        tabPersonalizedTimeConverter.setPreferredSize(new java.awt.Dimension(200, 35));
        tabPersonalizedTimeConverter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(237, 237, 237));
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 237, 237));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/personalize-time-converter.png"))); // NOI18N
        jLabel6.setText("PERSONALIZED TIME CONVERTER");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        tabPersonalizedTimeConverter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        bgtab.add(tabPersonalizedTimeConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 350, 60));

        tabTimeMasterSchedule.setBackground(new java.awt.Color(39, 39, 39));
        tabTimeMasterSchedule.setPreferredSize(new java.awt.Dimension(200, 35));
        tabTimeMasterSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(237, 237, 237));
        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(237, 237, 237));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/time_master_scheudule.png"))); // NOI18N
        jLabel7.setText("TIME MASTER SCHEDULE");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        tabTimeMasterSchedule.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabTimeMasterSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 350, 60));

        tabHistory.setBackground(new java.awt.Color(69, 69, 69));
        tabHistory.setPreferredSize(new java.awt.Dimension(200, 35));
        tabHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(237, 237, 237));
        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(237, 237, 237));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/history.png"))); // NOI18N
        jLabel8.setText("HISTORY");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        tabHistory.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 350, 60));

        tabSettings.setBackground(new java.awt.Color(39, 39, 39));
        tabSettings.setPreferredSize(new java.awt.Dimension(200, 35));
        tabSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(237, 237, 237));
        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(237, 237, 237));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jLabel9.setText("LOGOUT");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });
        tabSettings.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 350, 60));

        jPanel1.add(bgtab);
        bgtab.setBounds(0, 0, 350, 600);

        jPanel100.setBackground(new java.awt.Color(69, 69, 69));
        jPanel100.setLayout(null);

        timemasterscheduler.setFont(new java.awt.Font("Goudy Stout", 1, 20)); // NOI18N
        timemasterscheduler.setForeground(new java.awt.Color(237, 237, 237));
        timemasterscheduler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timemasterscheduler.setText("history");
        jPanel100.add(timemasterscheduler);
        timemasterscheduler.setBounds(0, 40, 650, 40);

        bgtimemasterscheduler.setBackground(new java.awt.Color(69, 69, 69));
        bgtimemasterscheduler.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 89, 89), 50, true));

        javax.swing.GroupLayout bgtimemasterschedulerLayout = new javax.swing.GroupLayout(bgtimemasterscheduler);
        bgtimemasterscheduler.setLayout(bgtimemasterschedulerLayout);
        bgtimemasterschedulerLayout.setHorizontalGroup(
            bgtimemasterschedulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        bgtimemasterschedulerLayout.setVerticalGroup(
            bgtimemasterschedulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel100.add(bgtimemasterscheduler);
        bgtimemasterscheduler.setBounds(30, 30, 585, 60);

        jScrollPane2.setBackground(new java.awt.Color(39, 39, 39));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "From Timezone", "To Timezone", "Date converted", "Time converted"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(237, 237, 237));
        jTable1.setSelectionBackground(new java.awt.Color(69, 69, 69));
        jTable1.setSelectionForeground(new java.awt.Color(237, 237, 237));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jPanel100.add(jScrollPane2);
        jScrollPane2.setBounds(10, 115, 630, 400);

        jButton2.setBackground(new java.awt.Color(39, 39, 39));
        jButton2.setFont(new java.awt.Font("Goudy Stout", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(237, 237, 237));
        jButton2.setText("CLEAR HISTORY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel100.add(jButton2);
        jButton2.setBounds(215, 540, 220, 30);

        jPanel1.add(jPanel100);
        jPanel100.setBounds(350, 0, 650, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1014, 637);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHome.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));

        Welcome WelcomeFrame = new Welcome();
        WelcomeFrame.setVisible(true);
        WelcomeFrame.pack();
        WelcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHome.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabGlobalTimeConverter.setBackground(clr);
        tabHome.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));

        GlobalTimeConverter GlobalTimeConverterFrame = new GlobalTimeConverter();
        GlobalTimeConverterFrame.setVisible(true);
        GlobalTimeConverterFrame.pack();
        GlobalTimeConverterFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabGlobalTimeConverter.setBackground(clr);
        tabHome.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabPersonalizedTimeConverter.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));

        PersonalizedTimeConverter PersonalizedTimeConverterFrame = new PersonalizedTimeConverter();
        PersonalizedTimeConverterFrame.setVisible(true);
        PersonalizedTimeConverterFrame.pack();
        PersonalizedTimeConverterFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabPersonalizedTimeConverter.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabTimeMasterSchedule.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));

        TimeMasterScheduler TimeMasterSchedulerFrame = new TimeMasterScheduler();
        TimeMasterSchedulerFrame.setVisible(true);
        TimeMasterSchedulerFrame.pack();
        TimeMasterSchedulerFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabTimeMasterSchedule.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHistory.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
        
        History HistoryFrame = new History();
        HistoryFrame.setVisible(true);
        HistoryFrame.pack();
        HistoryFrame.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHistory.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
        
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        UIManager.put("OptionPane.background", new Color (39,39,39));
        UIManager.put("Panel.background", new Color(69,69,69));
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("Button.background", new Color(69,69,69));
        UIManager.put("Button.foreground", new Color(247,247,247));
        
        JFrame frame = new JFrame("EXIT");
        
        int confirmed = JOptionPane.showConfirmDialog(frame, "Confirm if you want to LOGOUT", "LOGOUT Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (confirmed == JOptionPane.YES_OPTION) {
            Login LoginFrame = new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabSettings.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
        try {
            String sql ="DELETE FROM USERS";

            PreparedStatement stmt = con.prepareStatement(sql);

            int rows = stmt.executeUpdate();

            if (rows > 0) {
                System.out.println("All rows deleted successfully");
                DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();

                //buburahin lahat ng row sa table
                tbModel.setRowCount(0); 
            } else {
                System.out.println("No rows were deleted");
       
            }

            stmt.close();
                     
        } catch (SQLException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgtab;
    private javax.swing.JPanel bgtimemasterscheduler;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel tabFeatures;
    private javax.swing.JPanel tabGlobalTimeConverter;
    private javax.swing.JPanel tabHistory;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabPersonalizedTimeConverter;
    private javax.swing.JPanel tabSettings;
    private javax.swing.JPanel tabTimeMasterSchedule;
    private javax.swing.JLabel timemasterscheduler;
    // End of variables declaration//GEN-END:variables
}
