/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stern;


import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author calin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection con;
    public Login() {
        initComponents();
        createConnection();
    }
    void createConnection(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //connect the database
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ptcdb", "root", "Calingasanjohnerick01");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        loogo = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        loginlabel = new javax.swing.JLabel();
        emaillog = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        passwordlog = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        donthaveacclog = new javax.swing.JLabel();
        signuplogbtn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STERN");
        setPreferredSize(new java.awt.Dimension(1014, 635));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(39, 39, 39));
        Left.setPreferredSize(new java.awt.Dimension(500, 600));
        Left.setLayout(null);

        loogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\calin\\OneDrive\\Documents\\NetBeansProjects\\STERN\\src\\Icon\\logo(1).png")); // NOI18N
        loogo.setAlignmentX(0.5F);
        loogo.setMaximumSize(new java.awt.Dimension(542, 500));
        loogo.setMinimumSize(new java.awt.Dimension(542, 500));
        loogo.setPreferredSize(new java.awt.Dimension(500, 500));
        Left.add(loogo);
        loogo.setBounds(47, 70, 400, 400);

        jPanel1.add(Left);
        Left.setBounds(0, 0, 500, 600);

        Right.setBackground(new java.awt.Color(65, 65, 65));
        Right.setPreferredSize(new java.awt.Dimension(500, 600));
        Right.setLayout(null);

        loginlabel.setBackground(new java.awt.Color(237, 237, 237));
        loginlabel.setFont(new java.awt.Font("Goudy Stout", 1, 36)); // NOI18N
        loginlabel.setForeground(new java.awt.Color(255, 255, 255));
        loginlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlabel.setText("LOGIN");
        Right.add(loginlabel);
        loginlabel.setBounds(0, 100, 500, 50);

        emaillog.setBackground(new java.awt.Color(237, 237, 237));
        emaillog.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        emaillog.setForeground(new java.awt.Color(237, 237, 237));
        emaillog.setText("Email");
        Right.add(emaillog);
        emaillog.setBounds(75, 190, 190, 22);

        email.setBackground(new java.awt.Color(80, 80, 80));
        email.setFont(new java.awt.Font("RomanD", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(237, 237, 237));
        email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email.setToolTipText("Enter Your Email");
        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 80, 80), 5, true));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        Right.add(email);
        email.setBounds(75, 220, 358, 35);

        passwordlog.setBackground(new java.awt.Color(237, 237, 237));
        passwordlog.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        passwordlog.setForeground(new java.awt.Color(237, 237, 237));
        passwordlog.setText("Password");
        Right.add(passwordlog);
        passwordlog.setBounds(75, 280, 346, 22);

        loginbtn.setBackground(new java.awt.Color(39, 39, 39));
        loginbtn.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(237, 237, 237));
        loginbtn.setText("LOGIN");
        loginbtn.setToolTipText("click");
        loginbtn.setAlignmentX(0.5F);
        loginbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 80, 80), 3, true));
        loginbtn.setMinimumSize(new java.awt.Dimension(110, 25));
        loginbtn.setPreferredSize(new java.awt.Dimension(110, 25));
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnMouseExited(evt);
            }
        });
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        Right.add(loginbtn);
        loginbtn.setBounds(195, 377, 110, 25);

        donthaveacclog.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        donthaveacclog.setForeground(new java.awt.Color(237, 237, 237));
        donthaveacclog.setText("Don’t have an account ?");
        donthaveacclog.setPreferredSize(new java.awt.Dimension(195, 12));
        Right.add(donthaveacclog);
        donthaveacclog.setBounds(70, 418, 230, 30);

        signuplogbtn.setBackground(new java.awt.Color(65, 65, 65));
        signuplogbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        signuplogbtn.setForeground(new java.awt.Color(237, 237, 237));
        signuplogbtn.setText("Create account");
        signuplogbtn.setBorder(null);
        signuplogbtn.setPreferredSize(new java.awt.Dimension(57, 12));
        signuplogbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signuplogbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signuplogbtnMouseExited(evt);
            }
        });
        signuplogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signuplogbtnActionPerformed(evt);
            }
        });
        Right.add(signuplogbtn);
        signuplogbtn.setBounds(290, 418, 150, 30);

        password.setBackground(new java.awt.Color(80, 80, 80));
        password.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        password.setForeground(new java.awt.Color(237, 237, 237));
        password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        password.setToolTipText("Enter Your Password");
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 80, 80), 5, true));
        Right.add(password);
        password.setBounds(75, 310, 358, 35);

        jLabel6.setBackground(new java.awt.Color(237, 237, 237));
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 237, 237));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hello, Welcome back!");
        Right.add(jLabel6);
        jLabel6.setBounds(0, 150, 500, 17);

        jPanel1.add(Right);
        Right.setBounds(500, 0, 500, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("LOGIN");

        getAccessibleContext().setAccessibleName("Login");

        setSize(new java.awt.Dimension(1029, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here (LOG IN BUTTON):
        
        String email1 = email.getText();
        String password = String.valueOf(this.password.getPassword());

        try {
            String sql = "SELECT * FROM USER WHERE Email = ? AND Password = ?";
            PreparedStatement stmt = con.prepareStatement(sql);

            stmt.setString(1, email1);
            stmt.setString(2, password);
            
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                
                Welcome WelcomeFrame = new Welcome();
                WelcomeFrame.setVisible(true);
                WelcomeFrame.pack();
                WelcomeFrame.setLocationRelativeTo(null);
                this.dispose();
                
            } else {
                UIManager.put("OptionPane.background", new Color (39,39,39));
                UIManager.put("Panel.background", new Color(69,69,69));
                UIManager.put("OptionPane.messageForeground", Color.WHITE);
                JOptionPane.showMessageDialog(null, "Invalid Email or Password","Login Error",2);
            }
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void signuplogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signuplogbtnActionPerformed
        // TODO add your handling code here (IF YOU DON'T HAVE AN ACCOUNT SIGN UP BUTTON):
        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_signuplogbtnActionPerformed

    private void loginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseEntered
        // TODO add your handling code here:
        loginbtn.setBackground(new Color(255, 234, 0));
        loginbtn.setForeground(new Color (0,0,0));
    }//GEN-LAST:event_loginbtnMouseEntered

    private void loginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseExited
        // TODO add your handling code here:
        loginbtn.setBackground(new Color(39, 39, 39));
        loginbtn.setForeground(new Color (240,240,240));
    }//GEN-LAST:event_loginbtnMouseExited

    private void signuplogbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplogbtnMouseEntered
        // TODO add your handling code here:
        signuplogbtn.setForeground(new Color (255, 234, 0));
    }//GEN-LAST:event_signuplogbtnMouseEntered

    private void signuplogbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplogbtnMouseExited
        // TODO add your handling code here:
        signuplogbtn.setForeground(new Color (237,237,237));
    }//GEN-LAST:event_signuplogbtnMouseExited

    /**
     * @param args the command line arguments
     */
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel donthaveacclog;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emaillog;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JLabel loogo;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordlog;
    private javax.swing.JButton signuplogbtn;
    // End of variables declaration//GEN-END:variables
}
