/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stern;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import java.util.Timer;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author calin
 */
public class TimeMasterScheduler extends javax.swing.JFrame{
    
    Player player;
    

    /**
     * Creates new form TimeMasterScheduler
     */
    public TimeMasterScheduler() {
        initComponents();
        Thread t = new Thread(){
                           
            public void run()
                {
                while (true)
                {
                    DateFormat timeformat = new SimpleDateFormat("HH:mm:ss");  
                     
                    
                    String timeString = timeformat.format(new Date()).toString();
                    
                    
                    timedisplay.setText(timeString);
                    String time = timedisplay.getText();
                    
                    try{
                        Thread.sleep(1000);
                    }
                    catch(Exception e)
                    {

                    }
                }
            }
        };
        t.start();    
    }
    public void startAlarm(){
        try {
            File file = new File("Alarm Clock - Beep Alarm for 1 Minute.mp3");
            String sound = file.getAbsolutePath();
            FileInputStream fileInputStream = new FileInputStream(sound);
            player = new Player(fileInputStream);

            // para malaman na nag riring na
            

            player.play();
        } catch (FileNotFoundException | JavaLayerException e) {
            System.out.println("Error playing MP3 file: " + e);
        }
    }
    public void stopAlarm(){
        if(player!=null){
            player.close();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgtab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tabFeatures = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tabGlobalTimeConverter = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabPersonalizedTimeConverter = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tabTimeMasterSchedule = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tabHistory = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tabExit = new javax.swing.JPanel();
        tabExit1 = new javax.swing.JLabel();
        jPanel100 = new javax.swing.JPanel();
        timemasterscheduler = new javax.swing.JLabel();
        bgtimemasterscheduler = new javax.swing.JPanel();
        hour = new javax.swing.JTextField();
        min = new javax.swing.JTextField();
        sec = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        line = new javax.swing.JPanel();
        timedisplay = new javax.swing.JLabel();
        colon2 = new javax.swing.JLabel();
        colon1 = new javax.swing.JLabel();
        set1 = new javax.swing.JLabel();
        set2 = new javax.swing.JLabel();
        set3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        result = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1014, 635));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(null);

        bgtab.setBackground(new java.awt.Color(39, 39, 39));
        bgtab.setPreferredSize(new java.awt.Dimension(350, 600));
        bgtab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\calin\\OneDrive\\Documents\\NetBeansProjects\\STERN\\src\\Icon\\logo(welcome).png")); // NOI18N
        bgtab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        tabHome.setBackground(new java.awt.Color(39, 39, 39));
        tabHome.setPreferredSize(new java.awt.Dimension(200, 35));

        jLabel2.setBackground(new java.awt.Color(237, 237, 237));
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(237, 237, 237));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        jLabel2.setText("HOME");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout tabHomeLayout = new javax.swing.GroupLayout(tabHome);
        tabHome.setLayout(tabHomeLayout);
        tabHomeLayout.setHorizontalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tabHomeLayout.setVerticalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgtab.add(tabHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 350, 60));

        tabFeatures.setBackground(new java.awt.Color(39, 39, 39));
        tabFeatures.setPreferredSize(new java.awt.Dimension(200, 35));
        tabFeatures.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(237, 237, 237));
        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 237, 237));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("FEATURES");
        tabFeatures.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 350, 60));

        tabGlobalTimeConverter.setBackground(new java.awt.Color(39, 39, 39));
        tabGlobalTimeConverter.setPreferredSize(new java.awt.Dimension(200, 35));
        tabGlobalTimeConverter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(237, 237, 237));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 237, 237));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/global_time_converter.png"))); // NOI18N
        jLabel5.setText("GLOBAL TIME CONVERTER");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        tabGlobalTimeConverter.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabGlobalTimeConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 350, 60));

        tabPersonalizedTimeConverter.setBackground(new java.awt.Color(39, 39, 39));
        tabPersonalizedTimeConverter.setPreferredSize(new java.awt.Dimension(200, 35));
        tabPersonalizedTimeConverter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(237, 237, 237));
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 237, 237));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/personalize-time-converter.png"))); // NOI18N
        jLabel6.setText("PERSONALIZED TIME CONVERTER");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        tabPersonalizedTimeConverter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        bgtab.add(tabPersonalizedTimeConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 350, 60));

        tabTimeMasterSchedule.setBackground(new java.awt.Color(69, 69, 69));
        tabTimeMasterSchedule.setPreferredSize(new java.awt.Dimension(200, 35));
        tabTimeMasterSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(237, 237, 237));
        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(237, 237, 237));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/time_master_scheudule.png"))); // NOI18N
        jLabel7.setText("TIME MASTER SCHEDULER");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        tabTimeMasterSchedule.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabTimeMasterSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 350, 60));

        tabHistory.setBackground(new java.awt.Color(39, 39, 39));
        tabHistory.setPreferredSize(new java.awt.Dimension(200, 35));
        tabHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(237, 237, 237));
        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(237, 237, 237));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/history.png"))); // NOI18N
        jLabel8.setText("HISTORY");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        tabHistory.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 350, 60));

        tabExit.setBackground(new java.awt.Color(39, 39, 39));
        tabExit.setPreferredSize(new java.awt.Dimension(200, 35));
        tabExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabExit1.setBackground(new java.awt.Color(237, 237, 237));
        tabExit1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tabExit1.setForeground(new java.awt.Color(237, 237, 237));
        tabExit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        tabExit1.setText("LOGOUT");
        tabExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabExit1MouseEntered(evt);
            }
        });
        tabExit.add(tabExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 350, 60));

        jPanel1.add(bgtab);
        bgtab.setBounds(0, 0, 350, 600);

        jPanel100.setBackground(new java.awt.Color(69, 69, 69));
        jPanel100.setLayout(null);

        timemasterscheduler.setFont(new java.awt.Font("Goudy Stout", 1, 20)); // NOI18N
        timemasterscheduler.setForeground(new java.awt.Color(237, 237, 237));
        timemasterscheduler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timemasterscheduler.setText("TIME MASTER SCHEDULER");
        jPanel100.add(timemasterscheduler);
        timemasterscheduler.setBounds(0, 40, 650, 40);

        bgtimemasterscheduler.setBackground(new java.awt.Color(69, 69, 69));
        bgtimemasterscheduler.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 89, 89), 50, true));

        javax.swing.GroupLayout bgtimemasterschedulerLayout = new javax.swing.GroupLayout(bgtimemasterscheduler);
        bgtimemasterscheduler.setLayout(bgtimemasterschedulerLayout);
        bgtimemasterschedulerLayout.setHorizontalGroup(
            bgtimemasterschedulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        bgtimemasterschedulerLayout.setVerticalGroup(
            bgtimemasterschedulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel100.add(bgtimemasterscheduler);
        bgtimemasterscheduler.setBounds(30, 30, 585, 60);

        hour.setBackground(new java.awt.Color(69, 69, 69));
        hour.setFont(new java.awt.Font("Goudy Stout", 1, 48)); // NOI18N
        hour.setForeground(new java.awt.Color(237, 237, 237));
        hour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hour.setText("00");
        hour.setToolTipText("Enter the hour.");
        hour.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        hour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourActionPerformed(evt);
            }
        });
        hour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hourKeyPressed(evt);
            }
        });
        jPanel100.add(hour);
        hour.setBounds(145, 180, 100, 70);

        min.setBackground(new java.awt.Color(69, 69, 69));
        min.setFont(new java.awt.Font("Goudy Stout", 1, 48)); // NOI18N
        min.setForeground(new java.awt.Color(237, 237, 237));
        min.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        min.setText("00");
        min.setToolTipText("Enter the minute.");
        min.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        min.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                minKeyPressed(evt);
            }
        });
        jPanel100.add(min);
        min.setBounds(265, 180, 100, 70);

        sec.setBackground(new java.awt.Color(69, 69, 69));
        sec.setFont(new java.awt.Font("Goudy Stout", 1, 48)); // NOI18N
        sec.setForeground(new java.awt.Color(237, 237, 237));
        sec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sec.setText("00");
        sec.setToolTipText("Enter the seconds.");
        sec.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });
        sec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                secKeyPressed(evt);
            }
        });
        jPanel100.add(sec);
        sec.setBounds(385, 180, 100, 70);

        jButton1.setBackground(new java.awt.Color(69, 69, 69));
        jButton1.setFont(new java.awt.Font("Goudy Stout", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(237, 237, 237));
        jButton1.setText("SET ALARM");
        jButton1.setToolTipText("Tap to set the alarm.");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel100.add(jButton1);
        jButton1.setBounds(225, 300, 200, 30);

        line.setBackground(new java.awt.Color(237, 237, 237));
        line.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 237, 237), 2000, true));
        line.setForeground(new java.awt.Color(237, 237, 237));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel100.add(line);
        line.setBounds(30, 315, 585, 2);

        timedisplay.setFont(new java.awt.Font("Goudy Stout", 0, 80)); // NOI18N
        timedisplay.setForeground(new java.awt.Color(237, 237, 237));
        timedisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timedisplay.setText("00:00:00");
        jPanel100.add(timedisplay);
        timedisplay.setBounds(0, 100, 650, 80);

        colon2.setFont(new java.awt.Font("Goudy Stout", 0, 48)); // NOI18N
        colon2.setForeground(new java.awt.Color(237, 237, 237));
        colon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colon2.setText(":");
        jPanel100.add(colon2);
        colon2.setBounds(365, 180, 20, 75);

        colon1.setFont(new java.awt.Font("Goudy Stout", 0, 48)); // NOI18N
        colon1.setForeground(new java.awt.Color(237, 237, 237));
        colon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colon1.setText(":");
        jPanel100.add(colon1);
        colon1.setBounds(245, 180, 20, 75);

        set1.setFont(new java.awt.Font("Goudy Stout", 0, 30)); // NOI18N
        set1.setForeground(new java.awt.Color(237, 237, 237));
        set1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel100.add(set1);
        set1.setBounds(50, 410, 550, 100);

        set2.setFont(new java.awt.Font("Goudy Stout", 0, 35)); // NOI18N
        set2.setForeground(new java.awt.Color(237, 237, 237));
        set2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set2.setToolTipText("");
        jPanel100.add(set2);
        set2.setBounds(50, 370, 550, 100);

        set3.setFont(new java.awt.Font("Goudy Stout", 0, 35)); // NOI18N
        set3.setForeground(new java.awt.Color(237, 237, 237));
        set3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set3.setToolTipText("");
        jPanel100.add(set3);
        set3.setBounds(50, 450, 550, 100);

        jLabel19.setFont(new java.awt.Font("Goudy Stout", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(237, 237, 237));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/half-globe-home.png"))); // NOI18N
        jPanel100.add(jLabel19);
        jLabel19.setBounds(0, 254, 650, 346);

        result.setBackground(new java.awt.Color(69, 69, 69));
        result.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 89, 89), 125, true));

        javax.swing.GroupLayout resultLayout = new javax.swing.GroupLayout(result);
        result.setLayout(resultLayout);
        resultLayout.setHorizontalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        resultLayout.setVerticalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel100.add(result);
        result.setBounds(30, 370, 585, 180);

        jPanel1.add(jPanel100);
        jPanel100.setBounds(350, 0, 650, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1014, 637);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHome.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));

        Welcome WelcomeFrame = new Welcome();
        WelcomeFrame.setVisible(true);
        WelcomeFrame.pack();
        WelcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHome.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabGlobalTimeConverter.setBackground(clr);
        tabHome.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));

        GlobalTimeConverter GlobalTimeConverterFrame = new GlobalTimeConverter();
        GlobalTimeConverterFrame.setVisible(true);
        GlobalTimeConverterFrame.pack();
        GlobalTimeConverterFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabGlobalTimeConverter.setBackground(clr);
        tabHome.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabPersonalizedTimeConverter.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));

        PersonalizedTimeConverter PersonalizedTimeConverterFrame = new PersonalizedTimeConverter();
        PersonalizedTimeConverterFrame.setVisible(true);
        PersonalizedTimeConverterFrame.pack();
        PersonalizedTimeConverterFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabPersonalizedTimeConverter.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabTimeMasterSchedule.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));
        
        TimeMasterScheduler TimeMasterSchedulerFrame = new TimeMasterScheduler();
        TimeMasterSchedulerFrame.setVisible(true);
        TimeMasterSchedulerFrame.pack();
        TimeMasterSchedulerFrame.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabTimeMasterSchedule.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHistory.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));
        
        History HistoryFrame = new History();
        HistoryFrame.setVisible(true);
        HistoryFrame.pack();
        HistoryFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHistory.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabExit.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void tabExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabExit1MouseClicked
        // TODO add your handling code here:
        UIManager.put("OptionPane.background", new Color (39,39,39));
        UIManager.put("Panel.background", new Color(69,69,69));
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("Button.background", new Color(69,69,69));
        UIManager.put("Button.foreground", new Color(247,247,247));
        
        JFrame frame = new JFrame("EXIT");
        
        int confirmed = JOptionPane.showConfirmDialog(frame, "Confirm if you want to LOGOUT", "LOGOUT Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (confirmed == JOptionPane.YES_OPTION) {
            Login LoginFrame = new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_tabExit1MouseClicked

    private void tabExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabExit1MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabExit.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_tabExit1MouseEntered

    private void hourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourActionPerformed
        // TODO add your handling code here:
        int hour1 = Integer.parseInt(hour.getText());
        if(hour1<10){
            hour.setText("0"+ hour1);
        }
        
    }//GEN-LAST:event_hourActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
        int min1 = Integer.parseInt(min.getText());
        if(min1<10){
            min.setText("0"+ min1);
        }
              
    }//GEN-LAST:event_minActionPerformed

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
        int sec1 = Integer.parseInt(sec.getText());
        if(sec1<10){
            hour.setText("0"+ sec1);
        }
        
    }//GEN-LAST:event_secActionPerformed

    private void hourKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hourKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
                
        //hindi makakapag enter sa text field if enter in is not a numeb
         if (Character.isLetter(c)) {
            hour.setEditable(false);
        } else if (Character.isDigit(c)) {
            // para ma check kung ang input is a numeric digit
            String currentText = hour.getText();
            if (currentText.length() < 2) {
                int currentValue = Integer.parseInt(currentText + Character.toString((char) c));
                if (currentValue <= 23) {
                    hour.setEditable(true);
                } else {
                    hour.setEditable(false);
                }
            } else {
                hour.setEditable(false);
            }
        } else {
            hour.setEditable(true);
        }

    }//GEN-LAST:event_hourKeyPressed

    private void minKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
                
        if (Character.isLetter(c)) {
            min.setEditable(false);
        } else if (Character.isDigit(c)) {
            // para ma Check kung ang input is a numeric digit
            String currentText = min.getText();
            if (currentText.length() < 2) {
                int currentValue = Integer.parseInt(currentText + Character.toString((char) c));
                if (currentValue <= 59) {
                    min.setEditable(true);
                } else {
                    min.setEditable(false);
                }
            } else {
                min.setEditable(false);
            }
        } else {
            min.setEditable(true);
        }
        
    }//GEN-LAST:event_minKeyPressed

    private void secKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
                
        if (Character.isLetter(c)) {
            sec.setEditable(false);
        } else if (Character.isDigit(c)) {
            String currentText = sec.getText();
            if (currentText.length() < 2) {
                int currentValue = Integer.parseInt(currentText + Character.toString((char) c));
                if (currentValue <= 59) {
                    sec.setEditable(true);
                } else {
                    sec.setEditable(false);
                }
            } else {
                sec.setEditable(false);
            }
        } else {
            sec.setEditable(true);
        }

    }//GEN-LAST:event_secKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Timer timer = new Timer(); //timer ng tunog ng alarm
        Timer timer2 = new Timer(); // duration of the sound
    
        LocalTime timenow = LocalTime.now(); 

        if(jButton1.getText().equals("SET ALARM")){ //button

            //para malaman kung anong oras ang sinet na alarm
            set1.setText("Alarm Set: "+hour.getText()+":"+min.getText()+":"+sec.getText());
            set2.setText("");
            set3.setText("");

            //pagkuha ng values ng sinet na alarm
            // yung mga times 60 ay para sa timer, by seconds kase
            int hour1, hourD, min1, minD, sec1, duration, hours, mins, secs;
            hour1 = Integer.parseInt(hour.getText());
            
            hourD = hour1 * 60 * 60;
            min1 = Integer.parseInt(min.getText());
            minD = min1 * 60;
            sec1 = Integer.parseInt(sec.getText());

            //pagkuha ng values ng local time when the alarm is set
            hours = timenow.getHour()*60*60;
            mins = timenow.getMinute()*60;
            secs = timenow.getSecond();

            // eto duration ng timer
            //total seconds alarmset minus total seconds time na sinet ang alarm
            duration = (hourD + minD + sec1)- (hours + mins + secs);
            if (duration <= 0){
                        stopAlarm();
                        set2.setText("Already past");
                        set3.setText("that time");
                        set1.setText("");
            }else{
            System.out.println(duration);
            //eto na timer
            
            timer.schedule(new TimerTask() {
                int counter = 0;
                int counter2 = 0;
                
                
                
                @Override
                public void run() { 
                    System.out.println("Timer: " + counter++);
                    
                    if (counter > duration){
                        timer2.schedule(new TimerTask() {
                            @Override
                            public void run() {


                                System.out.println(counter2++);

                                if (counter2 >60){
                                    stopAlarm();
                                    timer.cancel();
                                    jButton1.setText("SET ALARM");
                                    set1.setText("");
                                    set2.setText("");
                                    set3.setText("");
                                    hour.setText("00");
                                    min.setText("00");
                                    sec.setText("00"); 
                                }
                                
                            }
                        }, 0, 1000);
                        jButton1.setText("STOP ALARM");
                        set1.setText("Alarm Ringing");
                        set2.setText("");
                        set3.setText("");
                        startAlarm();
                        timer.cancel();
                        }
                }
        
            }, 0, 1000); 
        }
        }
        else if (jButton1.getText().equals("STOP ALARM")){
            timer.cancel();
            timer2.cancel();
            stopAlarm();
            jButton1.setText("SET ALARM");
            set1.setText("");
            set2.setText("");
            set3.setText("");
            hour.setText("00");
            min.setText("00");
            sec.setText("00");
            
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(255, 234, 0));
        jButton1.setForeground(new Color (0,0,0));
//        timemasterscheduler.setForeground(new Color(255, 234, 0));

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(89,89,89));
        jButton1.setForeground(new Color (240,240,240));
//        timemasterscheduler.setForeground(new Color(237, 237, 237));

    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeMasterScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeMasterScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeMasterScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeMasterScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeMasterScheduler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgtab;
    private javax.swing.JPanel bgtimemasterscheduler;
    private javax.swing.JLabel colon1;
    private javax.swing.JLabel colon2;
    private javax.swing.JTextField hour;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JPanel line;
    private javax.swing.JTextField min;
    private javax.swing.JPanel result;
    private javax.swing.JTextField sec;
    private javax.swing.JLabel set1;
    private javax.swing.JLabel set2;
    private javax.swing.JLabel set3;
    private javax.swing.JPanel tabExit;
    private javax.swing.JLabel tabExit1;
    private javax.swing.JPanel tabFeatures;
    private javax.swing.JPanel tabGlobalTimeConverter;
    private javax.swing.JPanel tabHistory;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabPersonalizedTimeConverter;
    private javax.swing.JPanel tabTimeMasterSchedule;
    private javax.swing.JLabel timedisplay;
    private javax.swing.JLabel timemasterscheduler;
    // End of variables declaration//GEN-END:variables
    
}
