/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stern;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;

/**
 *
 * @author calin
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    
    
    public Welcome() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgtab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabHome = new javax.swing.JPanel();
        tabHome1 = new javax.swing.JLabel();
        tabFeatures = new javax.swing.JPanel();
        tabFeatures1 = new javax.swing.JLabel();
        tabGlobalTimeConverter = new javax.swing.JPanel();
        tabGlobalTimeConverter1 = new javax.swing.JLabel();
        tabPersonalizedTimeConverter = new javax.swing.JPanel();
        tabPersonlaizedTimeConverter1 = new javax.swing.JLabel();
        tabTimeMasterSchedule = new javax.swing.JPanel();
        tabTimeMasterSchedule1 = new javax.swing.JLabel();
        tabHistory = new javax.swing.JPanel();
        tabHistory1 = new javax.swing.JLabel();
        tabSettings = new javax.swing.JPanel();
        tabSettings1 = new javax.swing.JLabel();
        jPanel100 = new javax.swing.JPanel();
        t1 = new javax.swing.JPanel();
        stern = new javax.swing.JLabel();
        sternmeaning = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        gtcShortcut = new javax.swing.JPanel();
        gtcShortcut1 = new javax.swing.JLabel();
        ptcShortcut = new javax.swing.JPanel();
        ptcShortcut1 = new javax.swing.JLabel();
        tmsShortcut = new javax.swing.JPanel();
        tmsShortcut1 = new javax.swing.JLabel();
        blackbg = new javax.swing.JPanel();
        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b01 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b02 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1014, 635));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(null);

        bgtab.setBackground(new java.awt.Color(39, 39, 39));
        bgtab.setMinimumSize(new java.awt.Dimension(350, 560));
        bgtab.setPreferredSize(new java.awt.Dimension(350, 600));
        bgtab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\calin\\OneDrive\\Documents\\NetBeansProjects\\STERN\\src\\Icon\\logo(welcome).png")); // NOI18N
        bgtab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        tabHome.setBackground(new java.awt.Color(69, 69, 69));
        tabHome.setPreferredSize(new java.awt.Dimension(200, 35));

        tabHome1.setBackground(new java.awt.Color(237, 237, 237));
        tabHome1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tabHome1.setForeground(new java.awt.Color(237, 237, 237));
        tabHome1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        tabHome1.setText("HOME");
        tabHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabHome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabHome1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout tabHomeLayout = new javax.swing.GroupLayout(tabHome);
        tabHome.setLayout(tabHomeLayout);
        tabHomeLayout.setHorizontalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tabHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tabHomeLayout.setVerticalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tabHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgtab.add(tabHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 350, 60));

        tabFeatures.setBackground(new java.awt.Color(39, 39, 39));
        tabFeatures.setPreferredSize(new java.awt.Dimension(200, 35));
        tabFeatures.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabFeatures1.setBackground(new java.awt.Color(237, 237, 237));
        tabFeatures1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tabFeatures1.setForeground(new java.awt.Color(237, 237, 237));
        tabFeatures1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabFeatures1.setText("FEATURES");
        tabFeatures.add(tabFeatures1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 350, 60));

        tabGlobalTimeConverter.setBackground(new java.awt.Color(39, 39, 39));
        tabGlobalTimeConverter.setPreferredSize(new java.awt.Dimension(200, 35));
        tabGlobalTimeConverter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabGlobalTimeConverter1.setBackground(new java.awt.Color(237, 237, 237));
        tabGlobalTimeConverter1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tabGlobalTimeConverter1.setForeground(new java.awt.Color(237, 237, 237));
        tabGlobalTimeConverter1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabGlobalTimeConverter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/global_time_converter.png"))); // NOI18N
        tabGlobalTimeConverter1.setText("GLOBAL TIME CONVERTER");
        tabGlobalTimeConverter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabGlobalTimeConverter1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabGlobalTimeConverter1MouseEntered(evt);
            }
        });
        tabGlobalTimeConverter.add(tabGlobalTimeConverter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabGlobalTimeConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 350, 60));

        tabPersonalizedTimeConverter.setBackground(new java.awt.Color(39, 39, 39));
        tabPersonalizedTimeConverter.setPreferredSize(new java.awt.Dimension(200, 35));
        tabPersonalizedTimeConverter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPersonlaizedTimeConverter1.setBackground(new java.awt.Color(237, 237, 237));
        tabPersonlaizedTimeConverter1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tabPersonlaizedTimeConverter1.setForeground(new java.awt.Color(237, 237, 237));
        tabPersonlaizedTimeConverter1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabPersonlaizedTimeConverter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/personalize-time-converter.png"))); // NOI18N
        tabPersonlaizedTimeConverter1.setText("PERSONALIZED TIME CONVERTER");
        tabPersonlaizedTimeConverter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPersonlaizedTimeConverter1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabPersonlaizedTimeConverter1MouseEntered(evt);
            }
        });
        tabPersonalizedTimeConverter.add(tabPersonlaizedTimeConverter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        bgtab.add(tabPersonalizedTimeConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 350, 60));

        tabTimeMasterSchedule.setBackground(new java.awt.Color(39, 39, 39));
        tabTimeMasterSchedule.setPreferredSize(new java.awt.Dimension(200, 35));
        tabTimeMasterSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabTimeMasterSchedule1.setBackground(new java.awt.Color(237, 237, 237));
        tabTimeMasterSchedule1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tabTimeMasterSchedule1.setForeground(new java.awt.Color(237, 237, 237));
        tabTimeMasterSchedule1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabTimeMasterSchedule1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/time_master_scheudule.png"))); // NOI18N
        tabTimeMasterSchedule1.setText("TIME MASTER SCHEDULER");
        tabTimeMasterSchedule1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTimeMasterSchedule1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabTimeMasterSchedule1MouseEntered(evt);
            }
        });
        tabTimeMasterSchedule.add(tabTimeMasterSchedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabTimeMasterSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 350, 60));

        tabHistory.setBackground(new java.awt.Color(39, 39, 39));
        tabHistory.setPreferredSize(new java.awt.Dimension(200, 35));
        tabHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabHistory1.setBackground(new java.awt.Color(237, 237, 237));
        tabHistory1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tabHistory1.setForeground(new java.awt.Color(237, 237, 237));
        tabHistory1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabHistory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/history.png"))); // NOI18N
        tabHistory1.setText("HISTORY");
        tabHistory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabHistory1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabHistory1MouseEntered(evt);
            }
        });
        tabHistory.add(tabHistory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 350, 60));

        tabSettings.setBackground(new java.awt.Color(39, 39, 39));
        tabSettings.setPreferredSize(new java.awt.Dimension(200, 35));
        tabSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabSettings1.setBackground(new java.awt.Color(237, 237, 237));
        tabSettings1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tabSettings1.setForeground(new java.awt.Color(237, 237, 237));
        tabSettings1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabSettings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        tabSettings1.setText("LOGOUT");
        tabSettings1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSettings1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabSettings1MouseEntered(evt);
            }
        });
        tabSettings.add(tabSettings1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        bgtab.add(tabSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 350, 60));

        jPanel1.add(bgtab);
        bgtab.setBounds(0, 0, 350, 600);

        jPanel100.setBackground(new java.awt.Color(255, 255, 255));
        jPanel100.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanel100.setLayout(new javax.swing.OverlayLayout(jPanel100));

        t1.setBackground(new java.awt.Color(65, 65, 65));
        t1.setPreferredSize(new java.awt.Dimension(650, 600));
        t1.setLayout(null);

        stern.setBackground(new java.awt.Color(237, 237, 237));
        stern.setFont(new java.awt.Font("Goudy Stout", 1, 60)); // NOI18N
        stern.setForeground(new java.awt.Color(237, 237, 237));
        stern.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stern.setText("S T E R N");
        t1.add(stern);
        stern.setBounds(0, 20, 650, 83);

        sternmeaning.setBackground(new java.awt.Color(237, 237, 237));
        sternmeaning.setFont(new java.awt.Font("Lucida Sans", 1, 22)); // NOI18N
        sternmeaning.setForeground(new java.awt.Color(237, 237, 237));
        sternmeaning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sternmeaning.setText("Synchronize Time, Eliminate Routine Nuisances");
        t1.add(sternmeaning);
        sternmeaning.setBounds(0, 100, 650, 30);

        jPanel9.setBackground(new java.awt.Color(237, 237, 237));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 237, 237), 2000, true));
        jPanel9.setForeground(new java.awt.Color(237, 237, 237));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        t1.add(jPanel9);
        jPanel9.setBounds(30, 150, 585, 2);

        gtcShortcut.setBackground(new java.awt.Color(69, 69, 69));
        gtcShortcut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 100, true));
        gtcShortcut.setForeground(new java.awt.Color(255, 255, 255));
        gtcShortcut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gtcShortcut1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gtcShortcut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gtc(welcome).png"))); // NOI18N
        gtcShortcut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gtcShortcut1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gtcShortcut1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gtcShortcut1MouseExited(evt);
            }
        });
        gtcShortcut.add(gtcShortcut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 25, -1, -1));

        t1.add(gtcShortcut);
        gtcShortcut.setBounds(13, 360, 200, 150);

        ptcShortcut.setBackground(new java.awt.Color(69, 69, 69));
        ptcShortcut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 100, true));
        ptcShortcut.setForeground(new java.awt.Color(237, 237, 237));
        ptcShortcut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ptcShortcut1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ptcShortcut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ptc(welcome).png"))); // NOI18N
        ptcShortcut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptcShortcut1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ptcShortcut1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ptcShortcut1MouseExited(evt);
            }
        });
        ptcShortcut.add(ptcShortcut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 25, -1, -1));

        t1.add(ptcShortcut);
        ptcShortcut.setBounds(225, 360, 200, 150);

        tmsShortcut.setBackground(new java.awt.Color(69, 69, 69));
        tmsShortcut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 237, 237), 100, true));
        tmsShortcut.setForeground(new java.awt.Color(237, 237, 237));
        tmsShortcut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tmsShortcut1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tmsShortcut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tms(welcome).png"))); // NOI18N
        tmsShortcut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmsShortcut1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tmsShortcut1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tmsShortcut1MouseExited(evt);
            }
        });
        tmsShortcut.add(tmsShortcut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 25, -1, -1));

        t1.add(tmsShortcut);
        tmsShortcut.setBounds(437, 360, 200, 150);

        blackbg.setBackground(new java.awt.Color(69, 69, 69));
        blackbg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 39, 39), 120, true));
        blackbg.setLayout(null);

        a1.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        a1.setForeground(new java.awt.Color(237, 237, 237));
        a1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        a1.setText("Welcome to Synchrononize Time Eliminate Routine Nuisances!        ");
        blackbg.add(a1);
        a1.setBounds(0, 15, 620, 20);

        a2.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        a2.setForeground(new java.awt.Color(237, 237, 237));
        a2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        a2.setText("        With  our app, you  can  effortlessly  manage  time  across  the globe. ");
        blackbg.add(a2);
        a2.setBounds(0, 40, 620, 20);

        a3.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        a3.setForeground(new java.awt.Color(237, 237, 237));
        a3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        a3.setText("        Whether   it's  converting  time  zones  to  fit  your  needs,  setting up");
        blackbg.add(a3);
        a3.setBounds(0, 65, 620, 20);

        a4.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        a4.setForeground(new java.awt.Color(237, 237, 237));
        a4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        a4.setText("        with  our  Time  Master  Scheduler,  or  personalizing  your  time zone");
        blackbg.add(a4);
        a4.setBounds(0, 90, 620, 20);

        a5.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        a5.setForeground(new java.awt.Color(237, 237, 237));
        a5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        a5.setText("        preferences,  STERN  is here  to  streamline  your daily   routine. Let's ");
        blackbg.add(a5);
        a5.setBounds(0, 115, 620, 20);

        a6.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        a6.setForeground(new java.awt.Color(237, 237, 237));
        a6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        a6.setText("        make time management a breeze!");
        blackbg.add(a6);
        a6.setBounds(0, 140, 620, 20);

        t1.add(blackbg);
        blackbg.setBounds(13, 165, 624, 180);

        b2.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        b2.setForeground(new java.awt.Color(237, 237, 237));
        b2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2.setText("Personlized Time ");
        t1.add(b2);
        b2.setBounds(225, 520, 200, 30);

        b01.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        b01.setForeground(new java.awt.Color(237, 237, 237));
        b01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b01.setText(" Converter");
        t1.add(b01);
        b01.setBounds(13, 540, 200, 30);

        b1.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        b1.setForeground(new java.awt.Color(237, 237, 237));
        b1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1.setText("Global Time");
        t1.add(b1);
        b1.setBounds(13, 520, 200, 30);

        b02.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        b02.setForeground(new java.awt.Color(237, 237, 237));
        b02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b02.setText(" Converter");
        t1.add(b02);
        b02.setBounds(225, 540, 200, 30);

        b3.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        b3.setForeground(new java.awt.Color(237, 237, 237));
        b3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3.setText("Time Master");
        t1.add(b3);
        b3.setBounds(437, 520, 200, 30);

        b03.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        b03.setForeground(new java.awt.Color(237, 237, 237));
        b03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b03.setText("Scheduler");
        t1.add(b03);
        b03.setBounds(437, 540, 200, 30);

        jPanel100.add(t1);

        jPanel1.add(jPanel100);
        jPanel100.setBounds(350, 0, 650, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("Home");

        setSize(new java.awt.Dimension(1014, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabHome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHome1MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHome.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_tabHome1MouseEntered

    private void tabHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHome1MouseClicked
        // TODO add your handling code here:
//        t1.setVisible(true);
//        t2.setVisible(false);
//        t3.setVisible(false);
//        t4.setVisible(false);
//        t5.setVisible(false);
//        t6.setVisible(false);
        Color clr = new Color (69,69,69);
        tabHome.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_tabHome1MouseClicked

    private void tabGlobalTimeConverter1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabGlobalTimeConverter1MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);      
        tabGlobalTimeConverter.setBackground(clr);
        tabHome.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_tabGlobalTimeConverter1MouseEntered

    private void tabGlobalTimeConverter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabGlobalTimeConverter1MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabGlobalTimeConverter.setBackground(clr);
        tabHome.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
                
        GlobalTimeConverter GlobalTimeConverterFrame = new GlobalTimeConverter();
        GlobalTimeConverterFrame.setVisible(true);
        GlobalTimeConverterFrame.pack();
        GlobalTimeConverterFrame.setLocationRelativeTo(null);
        this.dispose();

        
        
        
    }//GEN-LAST:event_tabGlobalTimeConverter1MouseClicked

    private void tabPersonlaizedTimeConverter1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPersonlaizedTimeConverter1MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabPersonalizedTimeConverter.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_tabPersonlaizedTimeConverter1MouseEntered

    private void tabPersonlaizedTimeConverter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPersonlaizedTimeConverter1MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabPersonalizedTimeConverter.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
        
        PersonalizedTimeConverter PersonalizedTimeConverterFrame = new PersonalizedTimeConverter();
        PersonalizedTimeConverterFrame.setVisible(true);
        PersonalizedTimeConverterFrame.pack();
        PersonalizedTimeConverterFrame.setLocationRelativeTo(null);
        this.dispose();
//        t1.setVisible(false);
//        t2.setVisible(false);
//        t3.setVisible(true);
//        t4.setVisible(false);
//        t5.setVisible(false);
//        t6.setVisible(false);
    }//GEN-LAST:event_tabPersonlaizedTimeConverter1MouseClicked

    private void tabTimeMasterSchedule1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTimeMasterSchedule1MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabTimeMasterSchedule.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_tabTimeMasterSchedule1MouseEntered

    private void tabTimeMasterSchedule1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTimeMasterSchedule1MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabTimeMasterSchedule.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
        
        TimeMasterScheduler TimeMasterSchedulerFrame = new TimeMasterScheduler();
        TimeMasterSchedulerFrame.setVisible(true);
        TimeMasterSchedulerFrame.pack();
        TimeMasterSchedulerFrame.setLocationRelativeTo(null);
        this.dispose();
//        t1.setVisible(false);
//        t2.setVisible(false);
//        t3.setVisible(false);
//        t4.setVisible(true);
//        t5.setVisible(false);
//        t6.setVisible(false);
    }//GEN-LAST:event_tabTimeMasterSchedule1MouseClicked

    private void tabHistory1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHistory1MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHistory.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
    }//GEN-LAST:event_tabHistory1MouseEntered

    private void tabHistory1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHistory1MouseClicked
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabHistory.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        tabSettings.setBackground(new Color(39,39,39));
        
        History HistoryFrame = new History();
        HistoryFrame.setVisible(true);
        HistoryFrame.pack();
        HistoryFrame.setLocationRelativeTo(null);
        this.dispose();
//        t1.setVisible(false);
//        t2.setVisible(false);
//        t3.setVisible(false);
//        t4.setVisible(false);
//        t5.setVisible(true);
//        t6.setVisible(false);
    }//GEN-LAST:event_tabHistory1MouseClicked

    private void tabSettings1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSettings1MouseEntered
        // TODO add your handling code here:
        Color clr = new Color (69,69,69);
        tabSettings.setBackground(clr);
        tabGlobalTimeConverter.setBackground(new Color(39,39,39));
        tabPersonalizedTimeConverter.setBackground(new Color(39,39,39));
        tabTimeMasterSchedule.setBackground(new Color(39,39,39));
        tabHistory.setBackground(new Color(39,39,39));
        tabHome.setBackground(new Color(39,39,39));
        
    }//GEN-LAST:event_tabSettings1MouseEntered

    private void tabSettings1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSettings1MouseClicked
        // TODO add your handling code here:
        UIManager.put("OptionPane.background", new Color (39,39,39));
        UIManager.put("Panel.background", new Color(69,69,69));
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("Button.background", new Color(69,69,69));
        UIManager.put("Button.foreground", new Color(247,247,247));
        
        JFrame frame = new JFrame("EXIT");
        
        int confirmed = JOptionPane.showConfirmDialog(frame, "Confirm if you want to LOGOUT", "LOGOUT Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (confirmed == JOptionPane.YES_OPTION) {
            Login LoginFrame = new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_tabSettings1MouseClicked

    private void tmsShortcut1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmsShortcut1MouseExited
        // TODO add your handling code here:
        Color borderColor = new Color (240,240,240);
        LineBorder lineBorder = new LineBorder(borderColor,100);
        tmsShortcut.setBorder(lineBorder);
        b3.setForeground(new Color(237,237,237));
        b03.setForeground(new Color(237,237,237));
    }//GEN-LAST:event_tmsShortcut1MouseExited

    private void tmsShortcut1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmsShortcut1MouseEntered
        // TODO add your handling code here:
        Color borderColor = new Color (255, 234, 0);
        LineBorder lineBorder = new LineBorder(borderColor,100);
        tmsShortcut.setBorder(lineBorder);
        b3.setForeground(new Color(255,234,0));
        b03.setForeground(new Color(255,234,0));
    }//GEN-LAST:event_tmsShortcut1MouseEntered

    private void tmsShortcut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmsShortcut1MouseClicked
        // TODO add your handling code here:
        TimeMasterScheduler TimeMasterSchedulerFrame = new TimeMasterScheduler();
        TimeMasterSchedulerFrame.setVisible(true);
        TimeMasterSchedulerFrame.pack();
        TimeMasterSchedulerFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_tmsShortcut1MouseClicked

    private void ptcShortcut1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptcShortcut1MouseExited
        // TODO add your handling code here:
        Color borderColor = new Color (240,240,240);
        LineBorder lineBorder = new LineBorder(borderColor,100);
        ptcShortcut.setBorder(lineBorder);
        b2.setForeground(new Color(237,237,237));
        b02.setForeground(new Color(237,237,237));
    }//GEN-LAST:event_ptcShortcut1MouseExited

    private void ptcShortcut1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptcShortcut1MouseEntered
        // TODO add your handling code here:
        Color borderColor = new Color (255, 234, 0);
        LineBorder lineBorder = new LineBorder(borderColor,100);
        ptcShortcut.setBorder(lineBorder);
        b2.setForeground(new Color(255,234,0));
        b02.setForeground(new Color(255,234,0));
    }//GEN-LAST:event_ptcShortcut1MouseEntered

    private void ptcShortcut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptcShortcut1MouseClicked
        // TODO add your handling code here:
        PersonalizedTimeConverter PersonalizedTimeConverterFrame = new PersonalizedTimeConverter();
        PersonalizedTimeConverterFrame.setVisible(true);
        PersonalizedTimeConverterFrame.pack();
        PersonalizedTimeConverterFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ptcShortcut1MouseClicked

    private void gtcShortcut1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gtcShortcut1MouseExited
        // TODO add your handling code here:
        Color borderColor = new Color (240,240,240);
        LineBorder lineBorder = new LineBorder(borderColor,100);
        gtcShortcut.setBorder(lineBorder);
        b1.setForeground(new Color(237,237,237));
        b01.setForeground(new Color(237,237,237));

        
    }//GEN-LAST:event_gtcShortcut1MouseExited

    private void gtcShortcut1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gtcShortcut1MouseEntered
        // TODO add your handling code here:
        Color borderColor = new Color (255, 234, 0);
        LineBorder lineBorder = new LineBorder(borderColor,100);
        gtcShortcut.setBorder(lineBorder);
        b1.setForeground(new Color(255,234,0));
        b01.setForeground(new Color(255,234,0));
    }//GEN-LAST:event_gtcShortcut1MouseEntered

    private void gtcShortcut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gtcShortcut1MouseClicked

        GlobalTimeConverter GlobalTimeConverterFrame = new GlobalTimeConverter();
        GlobalTimeConverterFrame.setVisible(true);
        GlobalTimeConverterFrame.pack();
        GlobalTimeConverterFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_gtcShortcut1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel b01;
    private javax.swing.JLabel b02;
    private javax.swing.JLabel b03;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JPanel bgtab;
    private javax.swing.JPanel blackbg;
    private javax.swing.JPanel gtcShortcut;
    private javax.swing.JLabel gtcShortcut1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel ptcShortcut;
    private javax.swing.JLabel ptcShortcut1;
    private javax.swing.JLabel stern;
    private javax.swing.JLabel sternmeaning;
    private javax.swing.JPanel t1;
    private javax.swing.JPanel tabFeatures;
    private javax.swing.JLabel tabFeatures1;
    private javax.swing.JPanel tabGlobalTimeConverter;
    private javax.swing.JLabel tabGlobalTimeConverter1;
    private javax.swing.JPanel tabHistory;
    private javax.swing.JLabel tabHistory1;
    private javax.swing.JPanel tabHome;
    private javax.swing.JLabel tabHome1;
    private javax.swing.JPanel tabPersonalizedTimeConverter;
    private javax.swing.JLabel tabPersonlaizedTimeConverter1;
    private javax.swing.JPanel tabSettings;
    private javax.swing.JLabel tabSettings1;
    private javax.swing.JPanel tabTimeMasterSchedule;
    private javax.swing.JLabel tabTimeMasterSchedule1;
    private javax.swing.JPanel tmsShortcut;
    private javax.swing.JLabel tmsShortcut1;
    // End of variables declaration//GEN-END:variables
}
